---
- name: Start Calico resources
  kube:
    name: "{{item.item.name}}"
    namespace: "kube-system"
    kubectl: "{{bin_dir}}/kubectl"
    resource: "{{item.item.type}}"
    filename: "{{kube_config_dir}}/{{item.item.file}}"
    state: "latest"
  with_items: "{{ calico_node_manifests.results }}"
  when: inventory_hostname == groups['kube-master'][0] and not item|skipped
