apiVersion: v1
kind: Service
metadata:
  name: cadvisor
  namespace: monitoring
  labels:
    name: cadvisor
  annotations:
    prometheus.io/scrape: 'true'
spec:
  type: NodePort
  ports:
  - name: http-metrics
    port: 8080
    nodePort: 31194
    targetPort: http-metrics
  selector:
    name: cadvisor

