kind: Service
apiVersion: v1
metadata:
  namespace: monitoring
  name: node-exporter
  labels:
    app: node-exporter
spec:
  type: NodePort
  ports:
  - port: 9100
    nodePort: 30910
  selector:
    name: node-exporter