---
dependencies:
  - role: kubernetes-apps/ansible
    tags:
      - apps

  - role: kubernetes-apps/kpm
    tags:
      - apps
      - kpm

  - role: kubernetes-apps/efk
    when: efk_enabled
    tags:
      - apps
      - efk

  - role: kubernetes-apps/helm
    when: helm_enabled
    tags:
      - apps
      - helm

  - role: kubernetes-apps/registry
    when: registry_enabled
    tags:
      - apps
      - registry

  # istio role should be last because it takes a long time to initialize and
  # will cause timeouts trying to start other addons.
  - role: kubernetes-apps/istio
    when: istio_enabled
    tags:
      - apps
      - istio

  - role: kubernetes-apps/persistent_volumes
    when: persistent_volumes_enabled
    tags:
      - apps
      - persistent_volumes
