apiVersion: apps/v1
kind: Deployment
metadata:
  name: vortex-server
  labels:
    app: vortex-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vortex-server
  template:
    metadata:
      labels:
        app: vortex-server
    spec:
      containers:
      - name: vortex-server
        image: sdnvortex/vortex:v0.1.1
        ports:
        - containerPort: 7890
