---
- name: check if atomic host
  stat:
    path: /run/ostree-booted
  register: ostree

- set_fact:
    is_atomic: "{{ ostree.stat.exists }}"

- set_fact:
    kube_cert_group: "kube"
  when: is_atomic

- import_tasks: set_resolv_facts.yml
  tags:
    - bootstrap-os
    - resolvconf
    - facts
