---
helm_enabled: false

# specify a dir and attach it to helm for HELM_HOME.
helm_home_dir: "/root/.helm"

# Deployment mode: host or docker
helm_deployment_type: host

# Do not download the local repository cache on helm init
helm_skip_refresh: false

# Set URL for stable repository
# helm_stable_repo_url: "https://kubernetes-charts.storage.googleapis.com"

# Set node selector options for Tiller Deployment manifest.
# tiller_node_selectors: "key1=val1,key2=val2"

# Override values for the Tiller Deployment manifest.
# tiller_override: "key1=val1,key2=val2"
