---
- name: install | Compare host kubelet with hyperkube container
  command: "{{ docker_bin_dir }}/docker run --rm -v {{ bin_dir }}:/systembindir {{ hyperkube_image_repo }}:{{ hyperkube_image_tag }} /usr/bin/cmp /hyperkube /systembindir/kubelet"
  register: kubelet_task_compare_result
  until: kubelet_task_compare_result.rc in [0,1,2]
  retries: 4
  delay: "{{ retry_stagger | random + 3 }}"
  changed_when: false
  failed_when: "kubelet_task_compare_result.rc not in [0,1,2]"
  tags:
    - hyperkube
    - upgrade

- name: install | Copy kubelet from hyperkube container
  command: "{{ docker_bin_dir }}/docker run --rm -v {{ bin_dir }}:/systembindir {{ hyperkube_image_repo }}:{{ hyperkube_image_tag }} /bin/cp -f /hyperkube /systembindir/kubelet"
  when: kubelet_task_compare_result.rc != 0
  register: kubelet_task_result
  until: kubelet_task_result.rc == 0
  retries: 4
  delay: "{{ retry_stagger | random + 3 }}"
  tags:
    - hyperkube
    - upgrade
  notify: restart kubelet

- name: install | Copy socat wrapper for Container Linux
  command: "{{ docker_bin_dir }}/docker run --rm -v {{ bin_dir }}:/opt/bin {{ install_socat_image_repo }}:{{ install_socat_image_tag }}"
  args:
    creates: "{{ bin_dir }}/socat"
  when: ansible_os_family in ['CoreOS', 'Container Linux by CoreOS']
