- name: delete instances
  vars:
    service_account_email:
    credentials_file:
    project_id: linker-aurora
    zone: asia-east-a
  gce: 
    instance_names: "{{ gce.instance_names }}"
    state: absent
  tags:
    - delete

