# get hostname and desired ip from inventory file
#
- debug:
  msg: "{{ host_vars[gce] }}"

  #- name: create gce disk
  #
  #- name: create gce
  #  vars:
  #    service_account_email:
  #    credentials_file:
  #    project_id: linker-aurora
  #    zone: asia-east-a
  #  gce:
  #    name: vortex
  #    num_instances: 3
  #    machine_type: n1-standard-2
  #    image-family: ubuntu-1604-lts
  #    disk-size: 100
  #    external_ip: ephemeral
  #    network: default
  #    disks:
  #      - name: 
  #    metadata : '{ "startup-script" : "apt-get update" }'
  #    state: present
  #  register: gce
  #
  #- name: Save host data
  #  add_host:
  #    hostname: "{{ item.public_ip }}"
  #    groupname: gce_instances_ips
  #  with_items: gce
  #
  #- name: Wait for SSH for instances
  #  wait_for:
  #    delay: 1
  #    host: "{{ item.public_ip }}"
  #    port: 22
  #    state: started
  #    timeout: 30
  #  with_items: "{{ gce.instance_data }}"
  #
  #- name: Configure Hosts
  #  hosts: gce_instances_ips
  #  become: yes
  #  become_method: sudo
  #  roles:
  #  tags:
  #    - config
  #
  #- name: inject SSH key
