apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "vortex-server.fullname" . }}
  labels:
    app: {{ template "vortex-server.name" . }}
    chart: {{ template "vortex-server.chart" . }}
    release: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "vortex-server.name" . }}
  template:
    metadata:
      labels:
        app: {{ template "vortex-server.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "sdnvortex/vortex:{{ .Values.image.tag }}"
        ports:
        - containerPort: 7890
