---
dependencies:
  - role: kubernetes-apps/external_provisioner/local_volume_provisioner
    when: local_volume_provisioner_enabled
    tags:
      - apps
      - local-volume-provisioner
      - external-provisioner

  - role: kubernetes-apps/external_provisioner/cephfs_provisioner
    when: cephfs_provisioner_enabled
    tags:
      - apps
      - cephfs-provisioner
      - external-provisioner
