---
- name: "Kibana | Write Kibana deployment"
  template:
    src: kibana-deployment.yml.j2
    dest: "{{ kube_config_dir }}/kibana-deployment.yaml"
  register: kibana_deployment_manifest

- name: "Kibana | Create Kibana deployment"
  kube:
    filename: "{{kube_config_dir}}/kibana-deployment.yaml"
    kubectl: "{{bin_dir}}/kubectl"
    name: "kibana-logging"
    namespace: "kube-system"
    resource: "deployment"
    state: "latest"
  with_items: "{{ kibana_deployment_manifest.changed }}"
  run_once: true

- name: "Kibana | Write Kibana service "
  template:
    src: kibana-service.yml.j2
    dest: "{{ kube_config_dir }}/kibana-service.yaml"
  register: kibana_service_manifest

- name: "Kibana | Create Kibana service"
  kube:
    filename: "{{kube_config_dir}}/kibana-service.yaml"
    kubectl: "{{bin_dir}}/kubectl"
    name: "kibana-logging"
    namespace: "kube-system"
    resource: "svc"
    state: "latest"
  with_items: "{{ kibana_service_manifest.changed }}"
  run_once: true
