kind: Service
apiVersion: v1
metadata:
  labels:
    app: prometheus
  name: prometheus-external
  namespace: vortex
spec:
  type: NodePort
  ports:
  - port: 9090
    targetPort: 9090
    nodePort: 30003
  selector:
    app: prometheus