---
# Limits
weave_memory_limits: 400M
weave_cpu_limits: 300m
weave_memory_requests: 64M
weave_cpu_requests: 10m

# This two variable are automatically changed by the weave's role, do not manually change these values
# To reset values :
# weave_seed: unset
# weave_peers: unset
weave_seed: uninitialized
weave_peers: uninitialized

# weave's network password for encryption
# if null then no network encryption
# you can use --extra-vars to pass the password in command line
weave_password: EnterPasswordHere

# Weave uses consensus mode by default
# Enabling seed mode allow to dynamically add or remove hosts
# https://www.weave.works/docs/net/latest/ipam/
weave_mode_seed: false

# Set the MTU of Weave (default 1376, Jumbo Frames: 8916)
weave_mtu: 1376

# this variable is use in seed mode
weave_ip_current_cluster: "{% for host in groups['k8s-cluster'] %}{{ hostvars[host]['ip'] | default(hostvars[host]['ansible_default_ipv4']['address']) }}{% if not loop.last %} {% endif %}{% endfor %}"
