apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  namespace: monitoring
  name: node-exporter
spec:
  template:
    metadata:
      name:  node-exporter
      labels:
        name: node-exporter
      annotations:
        prometheus.io.scrape: "true"
    spec:
      hostPID: true
      containers:
      - name:  node-exporter
        image: asia.gcr.io/linker-aurora/node-exporter:develop
        securityContext:
          privileged: true
        ports:
        - containerPort: 9100
