---
- name: set secret_changed
  command: /bin/true
  notify:
    - set secret_changed to true
    - clear kubeconfig for root user

- name: set secret_changed to true
  set_fact:
    secret_changed: true

- name: clear kubeconfig for root user
  file:
    path: /root/.kube/config
    state: absent
