---
apiVersion: v1
kind: Service
metadata:
  name: mongo
  labels:
    name: mongo
    service: mongo
  namespace: vortex
spec:
  ports:
  - port: 27017
    targetPort: 27017
  selector:
    service: mongo
