apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: mongo-statefulset
spec:
  serviceName: "mongo-statefulset"
  replicas: 3
  template:
    metadata:
      labels:
        service: mongo
        role: db
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: mongo-container
          resources:
            requests:
              cpu: 100m
          image: mongo
          command:
            - mongod
            - "--bind_ip"
            - 0.0.0.0
          ports:
            - containerPort: 27017

