---

- name: remove-node | Drain node except daemonsets resource
  command: >-
    {{ bin_dir }}/kubectl drain
      --force
      --ignore-daemonsets
      --grace-period {{ drain_grace_period }}
      --timeout {{ drain_timeout }}
      --delete-local-data {{ item }}
  with_items:
    - "{{ groups['kube-node'] }}"
  failed_when: false
  delegate_to: "{{ groups['kube-master'][0] }}"
  ignore_errors: yes
